# Global Variables and Options for Dynamic Skills Finder App

#' @importFrom arrow read_parquet
#' @importFrom dplyr arrange
#' @importFrom sysfonts font_add_google
#' @importFrom gdtools register_gfont
#' @importFrom showtext showtext_auto
#' @import gfonts

# Global variables and options
options(
  arrow.pull_as_vector = TRUE,
  encoding = "UTF-8",
  scipen = 999,
  shiny.maxRequestSize = 100 * 1024^2,
  shiny.usecairo = TRUE
)
format(Sys.time, "%S")

gdtools::register_gfont("Lexend")
sysfonts::font_add_google("Lexend", "Lexend")
showtext::showtext_auto()

# Enums and auxiliar lists
player_agg_basic_info_columns <- list(
  "season_name" = "Season",
  "competition_name" = "Competition",
  "team_shortname" = "Team",
  "positions" = "Positions",
  "age" = "Age",
  "matches_played" = "Matches played",
  "starts" = "Matches started"
)

player_agg_info_columns <- list(
  "season_name" = "Season",
  "competition_name" = "Competition",
  "team_shortname" = "Team",
  "player_name" = "Player name",
  "positions" = "Positions",
  "age" = "Age",
  "minutes_played" = "Min. played",
  "matches_played" = "Matches played",
  "starts" = "Matches started"
)

player_agg_metric_columns <- list(
  "off_ball_runs" = "Off-ball runs",
  "off_ball_runs_targeted" = "Targeted off-ball runs",
  "dropping_off_runs" = "Dropping-off runs",
  "dropping_off_runs_targeted" = "Targeted dropping-off runs",
  "coming_short_runs" = "Coming short runs",
  "coming_short_runs_targeted" = "Targeted coming short runs",
  "pulling_wide_runs" = "Pulling wide runs",
  "pulling_wide_runs_targeted" = "Targeted pulling wide runs",
  "pulling_half_space_runs" = "Pulling half space runs",
  "pulling_half_space_runs_targeted" = "Targeted pulling half space runs",
  "support_runs" = "Support_runs",
  "support_runs_targeted" = "Targeted support runs",
  "run_ahead_of_the_ball_runs" = "Run ahead of the ball runs",
  "run_ahead_of_the_ball_runs_targeted" = "Targeted run ahead of the ball runs",
  "overlap_runs" = "Overlap runs",
  "overlap_runs_targeted" = "Targeted overlap runs",
  "underlap_runs" = "Underlap runs",
  "underlap_runs_targeted" = "Targeted underlap runs",
  "behind_runs" = "Behind runs",
  "behind_runs_targeted" = "Targeted behind runs",
  "cross_receiver_runs" = "Cross receiver runs",
  "cross_receiver_runs_targeted" = "Targeted cross receiver runs",
  "on_ball_engagements" = "On-ball engagements",
  "pressures" = "Pressures",
  "recovery_pressures" = "Recovery-pressures",
  "counter_pressures" = "Counter pressures",
  "on_ball_engagement_recoveries" = "On-ball engagement recoveries",
  "pressure_recoveries" = "Pressure recoveries",
  "recovery_pressure_recoveries" = "Recovery-pressure recoveries",
  "counter_pressure_recoveries" = "Counter-pressure recoveries",
  "on_ball_engagements_high" = "High on-ball engagements",
  "on_ball_engagement_high_recoveries" = "High on-ball engagements recoveries",
  "pressures_high" = "High pressures",
  "pressure_high_recoveries" = "High pressure recoveries",
  "recovery_pressures_high" = "High recovery-pressures",
  "recovery_pressure_high_recoveries" = "High recovery-pressure recoveries",
  "counter_pressures_high" = "High counter-pressures",
  "counter_pressure_high_recoveries" = "High counter-pressure recoveries",
  "passing_option_score_avg" = "Passing option score average",
  "off_ball_runs_90" = "Off-ball runs per 90",
  "off_ball_runs_targeted_90" = "Targeted off-ball runs per 90",
  "dropping_off_runs_90" = "Dropping-off runs per 90",
  "dropping_off_runs_targeted_90" = " Targeted dropping-off runs per 90",
  "coming_short_runs_90" = "Coming short runs per 90",
  "coming_short_runs_targeted_90" = "Targeted coming short runs per 90",
  "pulling_wide_runs_90" = "Pulling wide runs per 90",
  "pulling_wide_runs_targeted_90" = "Targeted pulling wide runs per 90",
  "pulling_half_space_runs_90" = "Pulling half space runs per 90",
  "pulling_half_space_runs_targeted_90" = "Targeted pulling half space runs per 90",
  "support_runs_90" = "Support runs per 90",
  "support_runs_targeted_90" = "Targeted support runs per 90",
  "run_ahead_of_the_ball_runs_90" = "Run ahead of the ball runs per 90",
  "run_ahead_of_the_ball_runs_targeted_90" = "Targeted run ahead of the ball runs per 90",
  "overlap_runs_90" = "Overlap runs per 90",
  "overlap_runs_targeted_90" = "Targeted overlap runs per 90",
  "underlap_runs_90" = "Underlap runs per 90",
  "underlap_runs_targeted_90" = "Targeted underlap runs per 90",
  "behind_runs_90" = "Behind runs per 90",
  "behind_runs_targeted_90" = "Targeted behind runs per 90",
  "cross_receiver_runs_90" = "Cross receiver runs per 90",
  "cross_receiver_runs_targeted_90" = "Targeted cross receiver runs per 90",
  "on_ball_engagements_90" = "On-ball engagements per 90",
  "pressures_90" = "Pressures per 90",
  "recovery_pressures_90" = "Recovery-pressures per 90",
  "counter_pressures_90" = "Counter-pressures per 90",
  "on_ball_engagement_recoveries_90" = "On-ball engagement recoveries per 90",
  "pressure_recoveries_90" = "Pressure recoveries per 90",
  "recovery_pressure_recoveries_90" = "Recovery-pressure recoveries per 90",
  "counter_pressure_recoveries_90" = "Counter-pressure recoveries per 90",
  "on_ball_engagements_high_90" = "High on-ball engagements per 90",
  "on_ball_engagement_high_recoveries_90" = "High on-ball engagements recoveries per 90",
  "pressures_high_90" = "High pressures per 90",
  "pressure_high_recoveries_90" = "High pressure recoveries per 90",
  "recovery_pressures_high_90" = "High recovery-pressures per 90",
  "recovery_pressure_high_recoveries_90" = "High recovery-pressure recoveries per 90",
  "counter_pressures_high_90" = "High counter-pressures per 90",
  "counter_pressure_high_recoveries_90" = "High counter-pressure recoveries per 90",
  "off_ball_runs_targeted_pct" = "Targeted off-ball runs %",
  "dropping_off_runs_targeted_pct" = "Dropping-off_runs_targeted_pct",
  "coming_short_runs_targeted_pct" = "Targeted coming short runs %",
  "pulling_wide_runs_targeted_pct" = "Targeted pulling wide runs %",
  "pulling_half_space_runs_targeted_pct" = "Targeted pulling half space runs %",
  "support_runs_targeted_pct" = "Targeted support runs %",
  "run_ahead_of_the_ball_runs_targeted_pct" = "Targeted run ahead of the ball runs pct",
  "overlap_runs_targeted_pct" = "Targeted overlap runs %",
  "underlap_runs_targeted_pct" = "Targeted underlap runs %",
  "behind_runs_targeted_pct" = "Targeted behind runs %",
  "cross_receiver_runs_targeted_pct" = "Targeted cross receiver runs %",
  "on_ball_engagement_recoveries_pct" = "On-ball engagement recoveries %",
  "pressure_recoveries_pct" = "Pressure recoveries %",
  "recovery_pressure_recoveries_pct" = "Recovery-pressure recoveries %",
  "counter_pressure_recoveries_pct" = "Counter-pressure recoveries %",
  "on_ball_engagement_high_recoveries_pct" = "High on-ball engagement recoveries %",
  "pressure_high_recoveries_pct" = "High pressure recoveries %",
  "recovery_pressure_high_recoveries_pct" = "High recovery-pressure recoveries %",
  "counter_pressure_high_recoveries_pct" = "High counter-pressure recoveries %",
  "passes" = "Passes",
  "passes_completed" = "Completed passes",
  "pass_completion_pct" = "Pass completion %",
  "xpass_completion_avg" = "xPass completion average",
  "xpass_completion_completed_avg" = "xPass completion from completed passes average",
  "xthreat" = "xThreat",
  "xthreat_avg" = "xThreat average",
  "line_breaking_passes" = "Line-breaking passes",
  "line_breaking_passes_completed" = "Completed line-breaking passes",
  "first_line_breaking_passes" = "First line-breaking passes",
  "second_last_line_breaking_passes" = "Second last line-breaking passes",
  "last_line_breaking_passes" = "Last line-breaking passes",
  "first_line_breaking_passes_completed" = "Completed first line-breaking passes",
  "second_last_line_breaking_passes_completed" = "Completed second last line-breaking passes",
  "last_line_breaking_passes_completed" = "Completed last line-breaking passes",
  "ahead_passes" = "Ahead passes",
  "ahead_passes_completed" = "Completed ahead passes",
  "line_breaking_passes_90" = "Line-breaking passes per 90",
  "line_breaking_passes_completed_90" = "Completed line-breaking passes per 90",
  "first_line_breaking_passes_90" = "First line-breaking passes per 90",
  "second_last_line_breaking_passes_90" = "Second last line-breaking passes per 90",
  "last_line_breaking_passes_90" = "Last line-breaking passes per 90",
  "first_line_breaking_passes_completed_90" = "Completed first line-breaking passes per 90",
  "second_last_line_breaking_passes_completed_90" = "Completed second last line-breaking passes per 90",
  "last_line_breaking_passes_completed_90" = "Completed last line-breaking passes per 90",
  "passes_90" = "Passes per 90",
  "passes_completed_90" = "Completed passes per 90",
  "ahead_passes_90" = "Ahead passes per 90",
  "ahead_passes_completed_90" = "Completed ahead passes per 90"
)

team_agg_metric_columns <- list(
  "off_ball_runs" = "Off-ball runs",
  "off_ball_runs_targeted" = "Targeted off-ball runs",
  "dropping_off_runs" = "Dropping-off runs",
  "dropping_off_runs_targeted" = "Targeted dropping-off runs",
  "coming_short_runs" = "Coming short runs",
  "coming_short_runs_targeted" = "Targeted coming short runs",
  "pulling_wide_runs" = "Pulling wide runs",
  "pulling_wide_runs_targeted" = "Targeted pulling wide runs",
  "pulling_half_space_runs" = "Pulling half space runs",
  "pulling_half_space_runs_targeted" = "Targeted pulling half space runs",
  "support_runs" = "Support_runs",
  "support_runs_targeted" = "Targeted support runs",
  "run_ahead_of_the_ball_runs" = "Run ahead of the ball runs",
  "run_ahead_of_the_ball_runs_targeted" = "Targeted run ahead of the ball runs",
  "overlap_runs" = "Overlap runs",
  "overlap_runs_targeted" = "Targeted overlap runs",
  "underlap_runs" = "Underlap runs",
  "underlap_runs_targeted" = "Targeted underlap runs",
  "behind_runs" = "Behind runs",
  "behind_runs_targeted" = "Targeted behind runs",
  "cross_receiver_runs" = "Cross receiver runs",
  "cross_receiver_runs_targeted" = "Targeted cross receiver runs",
  "on_ball_engagements" = "On-ball engagements",
  "pressures" = "Pressures",
  "recovery_pressures" = "Recovery-pressures",
  "counter_pressures" = "Counter pressures",
  "on_ball_engagement_recoveries" = "On-ball engagement recoveries",
  "pressure_recoveries" = "Pressure recoveries",
  "recovery_pressure_recoveries" = "Recovery-pressure recoveries",
  "counter_pressure_recoveries" = "Counter-pressure recoveries",
  "on_ball_engagements_high" = "High on-ball engagements",
  "on_ball_engagement_high_recoveries" = "High on-ball engagement recoveries",
  "pressures_high" = "High pressures",
  "pressure_high_recoveries" = "High pressure recoveries",
  "recovery_pressures_high" = "High recovery-pressures",
  "recovery_pressure_high_recoveries" = "High recovery-pressure recoveries",
  "counter_pressures_high" = "High counter-pressures",
  "counter_pressure_high_recoveries" = "High counter-pressure recoveries",
  "recovery_height_avg" = "Recovery height average",
  "off_ball_runs_90" = "Off-ball runs per 90",
  "off_ball_runs_targeted_90" = "Targeted off-ball runs per 90",
  "dropping_off_runs_90" = "Dropping-off runs per 90",
  "dropping_off_runs_targeted_90" = " Targeted dropping-off runs per 90",
  "coming_short_runs_90" = "Coming short runs per 90",
  "coming_short_runs_targeted_90" = "Targeted coming short runs per 90",
  "pulling_wide_runs_90" = "Pulling wide runs per 90",
  "pulling_wide_runs_targeted_90" = "Targeted pulling wide runs per 90",
  "pulling_half_space_runs_90" = "Pulling half space runs per 90",
  "pulling_half_space_runs_targeted_90" = "Targeted pulling half space runs per 90",
  "support_runs_90" = "Support runs per 90",
  "support_runs_targeted_90" = "Targeted support runs per 90",
  "run_ahead_of_the_ball_runs_90" = "Run ahead of the ball runs per 90",
  "run_ahead_of_the_ball_runs_targeted_90" = "Targeted run ahead of the ball runs per 90",
  "overlap_runs_90" = "Overlap runs per 90",
  "overlap_runs_targeted_90" = "Targeted overlap runs per 90",
  "underlap_runs_90" = "Underlap runs per 90",
  "underlap_runs_targeted_90" = "Targeted underlap runs per 90",
  "behind_runs_90" = "Behind runs per 90",
  "behind_runs_targeted_90" = "Targeted behind runs per 90",
  "cross_receiver_runs_90" = "Cross receiver runs per 90",
  "cross_receiver_runs_targeted_90" = "Targeted cross receiver runs per 90",
  "on_ball_engagements_90" = "On-ball engagements per 90",
  "pressures_90" = "Pressures per 90",
  "recovery_pressures_90" = "Recovery-pressures per 90",
  "counter_pressures_90" = "Counter-pressures per 90",
  "on_ball_engagement_recoveries_90" = "On-ball engagement recoveries per 90",
  "pressure_recoveries_90" = "Pressure recoveries per 90",
  "recovery_pressure_recoveries_90" = "Recovery-pressure recoveries per 90",
  "counter_pressure_recoveries_90" = "Counter-pressure recoveries per 90",
  "on_ball_engagements_high_90" = "High on-ball engagements per 90",
  "on_ball_engagement_high_recoveries_90" = "High on-ball engagement recoveries per 90",
  "pressures_high_90" = "High pressures per 90",
  "pressure_high_recoveries_90" = "High pressure recoveries per 90",
  "recovery_pressures_high_90" = "High recovery-pressures per 90",
  "recovery_pressure_high_recoveries_90" = "High recovery-pressure recoveries per 90",
  "counter_pressures_high_90" = "High counter-pressures per 90",
  "counter_pressure_high_recoveries_90" = "High counter-pressure recoveries per 90",
  "off_ball_runs_targeted_pct" = "Targeted off-ball runs %",
  "dropping_off_runs_targeted_pct" = "Dropping-off_runs_targeted_pct",
  "coming_short_runs_targeted_pct" = "Targeted coming short runs %",
  "pulling_wide_runs_targeted_pct" = "Targeted pulling wide runs %",
  "pulling_half_space_runs_targeted_pct" = "Targeted pulling half space runs %",
  "support_runs_targeted_pct" = "Targeted support runs %",
  "run_ahead_of_the_ball_runs_targeted_pct" = "Targeted run ahead of the ball runs pct",
  "overlap_runs_targeted_pct" = "Targeted overlap runs %",
  "underlap_runs_targeted_pct" = "Targeted underlap runs %",
  "behind_runs_targeted_pct" = "Targeted behind runs %",
  "cross_receiver_runs_targeted_pct" = "Targeted cross receiver runs %",
  "on_ball_engagement_recoveries_pct" = "On-ball engagement recoveries %",
  "pressure_recoveries_pct" = "Pressure recoveries %",
  "recovery_pressure_recoveries_pct" = "Recovery-pressure recoveries %",
  "counter_pressure_recoveries_pct" = "Counter-pressure recoveries %",
  "on_ball_engagement_high_recoveries_pct" = "High on-ball engagements recoveries %",
  "pressure_high_recoveries_pct" = "High pressure recoveries %",
  "recovery_pressure_high_recoveries_pct" = "High recovery-pressure recoveries %",
  "counter_pressure_high_recoveries_pct" = "High counter-pressure recoveries %",
  "defense_recovery_height_avg" = "Defense line recovery height average",
  "midfield_recovery_height_avg" = "Midfield line recovery height average",
  "attack_recovery_height_avg" = "Attacking line recovery height average",
  "defense_recoveries" = "Defense line recoveries",
  "midfield_recoveries" = "Midfield line recoveries",
  "attack_recoveries" = "Attacking line recoveries"
)

player_agg_metric_types <- list(
  "minutes_played" = "INFO",
  "matches_played" = "INFO",
  "starts" = "INFO",
  "off_ball_runs" = "OBR",
  "off_ball_runs_targeted" = "OBR",
  "dropping_off_runs" = "OBR",
  "dropping_off_runs_targeted" = "OBR",
  "coming_short_runs" = "OBR",
  "coming_short_runs_targeted" = "OBR",
  "pulling_wide_runs" = "OBR",
  "pulling_wide_runs_targeted" = "OBR",
  "pulling_half_space_runs" = "OBR",
  "pulling_half_space_runs_targeted" = "OBR",
  "support_runs" = "OBR",
  "support_runs_targeted" = "OBR",
  "run_ahead_of_the_ball_runs" = "OBR",
  "run_ahead_of_the_ball_runs_targeted" = "OBR",
  "overlap_runs" = "OBR",
  "overlap_runs_targeted" = "OBR",
  "underlap_runs" = "OBR",
  "underlap_runs_targeted" = "OBR",
  "behind_runs" = "OBR",
  "behind_runs_targeted" = "OBR",
  "cross_receiver_runs" = "OBR",
  "cross_receiver_runs_targeted" = "OBR",
  "on_ball_engagements" = "OBE",
  "pressures" = "OBE",
  "recovery_pressures" = "OBE",
  "counter_pressures" = "OBE",
  "on_ball_engagement_recoveries" = "OBE",
  "pressure_recoveries" = "OBE",
  "recovery_pressure_recoveries" = "OBE",
  "counter_pressure_recoveries" = "OBE",
  "on_ball_engagements_high" = "OBE",
  "on_ball_engagement_high_recoveries" = "OBE",
  "pressures_high" = "OBE",
  "pressure_high_recoveries" = "OBE",
  "recovery_pressures_high" = "OBE",
  "recovery_pressure_high_recoveries" = "OBE",
  "counter_pressures_high" = "OBE",
  "counter_pressure_high_recoveries" = "OBE",
  "passing_option_score_avg" = "OBEv",
  "off_ball_runs_90" = "OBR",
  "off_ball_runs_targeted_90" = "OBR",
  "dropping_off_runs_90" = "OBR",
  "dropping_off_runs_targeted_90" = "OBR",
  "coming_short_runs_90" = "OBR",
  "coming_short_runs_targeted_90" = "OBR",
  "pulling_wide_runs_90" = "OBR",
  "pulling_wide_runs_targeted_90" = "OBR",
  "pulling_half_space_runs_90" = "OBR",
  "pulling_half_space_runs_targeted_90" = "OBR",
  "support_runs_90" = "OBR",
  "support_runs_targeted_90" = "OBR",
  "run_ahead_of_the_ball_runs_90" = "OBR",
  "run_ahead_of_the_ball_runs_targeted_90" = "OBR",
  "overlap_runs_90" = "OBR",
  "overlap_runs_targeted_90" = "OBR",
  "underlap_runs_90" = "OBR",
  "underlap_runs_targeted_90" = "OBR",
  "behind_runs_90" = "OBR",
  "behind_runs_targeted_90" = "OBR",
  "cross_receiver_runs_90" = "OBR",
  "cross_receiver_runs_targeted_90" = "OBR",
  "on_ball_engagements_90" = "OBE",
  "pressures_90" = "OBE",
  "recovery_pressures_90" = "OBE",
  "counter_pressures_90" = "OBE",
  "on_ball_engagement_recoveries_90" = "OBE",
  "pressure_recoveries_90" = "OBE",
  "recovery_pressure_recoveries_90" = "OBE",
  "counter_pressure_recoveries_90" = "OBE",
  "on_ball_engagements_high_90" = "OBE",
  "on_ball_engagement_high_recoveries_90" = "OBE",
  "pressures_high_90" = "OBE",
  "pressure_high_recoveries_90" = "OBE",
  "recovery_pressures_high_90" = "OBE",
  "recovery_pressure_high_recoveries_90" = "OBE",
  "counter_pressures_high_90" = "OBE",
  "counter_pressure_high_recoveries_90" = "OBE",
  "off_ball_runs_targeted_pct" = "OBR",
  "dropping_off_runs_targeted_pct" = "OBR",
  "coming_short_runs_targeted_pct" = "OBR",
  "pulling_wide_runs_targeted_pct" = "OBR",
  "pulling_half_space_runs_targeted_pct" = "OBR",
  "support_runs_targeted_pct" = "OBR",
  "run_ahead_of_the_ball_runs_targeted_pct" = "OBR",
  "overlap_runs_targeted_pct" = "OBR",
  "underlap_runs_targeted_pct" = "OBR",
  "behind_runs_targeted_pct" = "OBR",
  "cross_receiver_runs_targeted_pct" = "OBR",
  "on_ball_engagement_recoveries_pct" = "OBE",
  "pressure_recoveries_pct" = "OBE",
  "recovery_pressure_recoveries_pct" = "OBE",
  "counter_pressure_recoveries_pct" = "OBE",
  "on_ball_engagement_high_recoveries_pct" = "OBE",
  "pressure_high_recoveries_pct" = "OBE",
  "recovery_pressure_high_recoveries_pct" = "OBE",
  "counter_pressure_high_recoveries_pct" = "OBE",
  "passes" = "OBEv",
  "passes_completed" = "OBEv",
  "pass_completion_pct" = "OBEv",
  "xpass_completion_avg" = "OBEv",
  "xpass_completion_completed_avg" = "OBEv",
  "xthreat" = "OBEv",
  "xthreat_avg" = "OBEv",
  "line_breaking_passes" = "OBEv",
  "line_breaking_passes_completed" = "OBEv",
  "first_line_breaking_passes" = "OBEv",
  "second_last_line_breaking_passes" = "OBEv",
  "last_line_breaking_passes" = "OBEv",
  "first_line_breaking_passes_completed" = "OBEv",
  "second_last_line_breaking_passes_completed" = "OBEv",
  "last_line_breaking_passes_completed" = "OBEv",
  "ahead_passes" = "OBEv",
  "ahead_passes_completed" = "OBEv",
  "line_breaking_passes_90" = "OBEv",
  "line_breaking_passes_completed_90" = "OBEv",
  "first_line_breaking_passes_90" = "OBEv",
  "second_last_line_breaking_passes_90" = "OBEv",
  "last_line_breaking_passes_90" = "OBEv",
  "first_line_breaking_passes_completed_90" = "OBEv",
  "second_last_line_breaking_passes_completed_90" = "OBEv",
  "last_line_breaking_passes_completed_90" = "OBEv",
  "passes_90" = "OBEv",
  "passes_completed_90" = "OBEv",
  "ahead_passes_90" = "OBEv",
  "ahead_passes_completed_90" = "OBEv"
)

# Load initial data
tracking_data <- arrow::read_parquet(
  "inst/extdata/tracking.parquet",
  as_data_frame = FALSE
)

dynamic_events_data <- arrow::read_parquet(
  "inst/extdata/dynamic_events.parquet",
  as_data_frame = FALSE
)

team_aggregates_data <- arrow::read_parquet(
  "inst/extdata/agg_team.parquet",
  as_data_frame = FALSE
) |>
  dplyr::arrange(team_shortname)

player_aggregates_data <- arrow::read_parquet(
  "inst/extdata/agg_player.parquet",
  as_data_frame = FALSE
) |>
  dplyr::arrange(player_name)
